version: '3'
services:
  plex:
    container_name: plex_media
    network_mode: host
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_ID} # claim new pass every instance.
      - ADVERTISE_IP=http://${HOST_NAME}:32400/
      - PLEX_UID=${UID}
      - PLEX_GID=${GID}
    hostname: ${PLEX_HOST_NAME}
    volumes:
     - ${CONFIG_FOLDER}/plex/config:/config 
     - ${CONFIG_FOLDER}/plex/transcode:/transcode 
     - ${CONFIG_FOLDER}/plex/data:/data 
     - ${VIDEO_PATH}/movies:/movies 
     - ${VIDEO_PATH}/tvshows:/tvshows
     - ${IMAGES_PATH}:/images
     - ${MUSIC_PATH}:/music
     - /home/erlichsefi/external_hd:/external

  radarr:
    container_name: radarr
    network_mode: host
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
    - 7878:7878
    volumes:
      - ${CONFIG_FOLDER}/radarr/:/config
      - ${VIDEO_PATH}/movies:/movies
      - ${DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    
 
  sonarr:
    container_name: sonarr
    network_mode: host
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ${CONFIG_FOLDER}/sonarr/:/config
      - ${VIDEO_PATH}/tvshows:/tv
      - ${DOWNLOAD_PATH}:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
  

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ${CONFIG_FOLDER}/Jackett/:/config
      - ${METADATA_PATH}/Jackett/downloads:/downloads
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission_media
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${CONFIG_FOLDER}/transmission/torrent_config/:/config 
      - ${CONFIG_FOLDER}/transmission/torrent_watch:/watch
      - ${CONFIG_FOLDER}/transmission/scripts:/scripts
      - ${DOWNLOAD_PATH}:/downloads 

    ports:
      - 9090:9091
      - 51414:51414
      - 51414:51414/udp
    restart: unless-stopped